### ISSUE TITLE
ATG 11.2 Support Requested 

### ISSUE THREAD

**Issue by devondragon** [sparkred-insight/PayPalModule#1]
Minor changes in payment type handling between ATG 11.1 and 11.2 require some adjustments for a 11.2 compatible module.

{{15:03:11,776 ERROR [nucleusNamespace.atg.commerce.pricing.PaymentTypePromotionVetoer] (http-/0.0.0.0:8080-2) The order has an unidentified payment group type.
15:03:11,777 ERROR [nucleusNamespace.atg.commerce.payment.PaymentManager] (http-/0.0.0.0:8080-2) atg.commerce.payment.PaymentResources->NoPaymentTypePrrovider
15:03:11,777 ERROR [nucleusNamespace.atg.commerce.payment.PaymentManager] (http-/0.0.0.0:8080-2) No payment type provider for group of type: paypal
15:03:11,777 ERROR [nucleusNamespace.atg.commerce.pricing.PaymentTypePromotionVetoer] (http-/0.0.0.0:8080-2) Payment group has unsupported payment type.: atg.commerce.CommerceException: Payment group with type identifier paypal is unsupported.

I am thinking that this is because of version issue. ATG11.2 PaymentManager as additional code which is not there in ATG11.1

Here are few props which were added newly in PaymentManager ATG 11.2.
mPaymentGroupIdentifierToPaymentTypeProvider
mIncludePaymentGroupsWithoutOrderRelationship
mSupportedPaymentTypesByPaymentGroupIdentifier}}

**Comment by devondragon** [comment]
https://www.sparkred.com/jira/browse/ATGPP-43

**Comment by varshaasinghal** [comment]
I am also getting the same error after adding new payment group, can someone provide me the solution. 14:40:14,217 ERROR [nucleusNamespace.atg.commerce.payment.PaymentManager] (http-/0.0.0.0:8181-1) atg.commerce.payment.PaymentResources->NoPaymentTypePrrovider
14:40:14,217 ERROR [nucleusNamespace.atg.commerce.payment.PaymentManager] (http-/0.0.0.0:8181-1) No payment type provider for group of type: pointsPaymentGroup
14:40:14,221 ERROR [nucleusNamespace.atg.commerce.pricing.PaymentTypePromotionVetoer] (http-/0.0.0.0:8181-1) Payment group has unsupported payment type.: atg.commerce.CommerceException: Payment group with type identifier pointsPaymentGroup is unsupported.

**Comment by devondragon** [comment]
@LetGirlsCode  The fix was to add a mapping in the /atg/commerce/payment/PaymentManager component's paymentGroupIdentifierToPaymentTypeProvider property for your custom payment type.  If you don't need a custom manager, you can map it to the PaymentManger itself, like this:

`paymentGroupIdentifierToPaymentTypeProvider+=paypal\=/atg/commerce/payment/PaymentManager`
